experimentName: nni_example
trialConcurrency: 1
maxTrialNumber: 100
searchSpaceFile: search_space.json
trialCommand: python nerf2_runner.py --m unet1 --config configs/ble-rssi_U1.yml --dataset_type ble --gpu 2 --mode train --n nni
trialCodeDirectory: .
trialCodeDirectory: .
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
