experimentName: nni_example
trialConcurrency: 1
maxTrialNumber: 100
searchSpaceFile: search_space.json
trialCommand: python nerf2_runner.py --m vae --config configs/mimo-csi-onlyV.yml --dataset_type mimo --gpu 2 --mode train --n nni
trialCodeDirectory: .
trialCodeDirectory: .
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local