experimentName: nni_example
trialConcurrency: 1
maxTrialNumber: 100
searchSpaceFile: search_space.json
trialCommand: python nerf2_runner.py --m unet --config configs/ble-rssi-onlyU.yml --dataset_type ble --gpu 2 --mode train
trialCodeDirectory: .
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local