experimentName: nni_example
trialConcurrency: 1
maxTrialNumber: 100
searchSpaceFile: search_space.json
trialCommand: python nerf2_runner.py --m unet --config configs/rfid-spectrum.yml --dataset_type rfid --gpu 1 --mode train
trialCodeDirectory: .
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  gpuIndices: [0, 1, 2, 3]