experimentName: nni_example
trialConcurrency: 1
maxTrialNumber: 100
searchSpaceFile: search_space.json
trialCommand: python nerf2_runner.py --m mlp --config configs/ble-rssi-onlyMLP.yml --dataset_type ble --gpu 2 --mode train
trialCodeDirectory: .
trialCodeDirectory: .
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local