experimentName: nni_example
trialConcurrency: 1
maxTrialNumber: 100
searchSpaceFile: search_space.json
trialCommand: python nerf2_runner.py --m PPM --config configs/ble-rssi.yml --dataset_type ble --gpu 3 --mode train --n nni
trialCodeDirectory: .
trialCodeDirectory: .
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
