experimentName: nni_example
trialConcurrency: 1
maxTrialNumber: 100
searchSpaceFile: search_space.json
trialCommand: python nerf2_runner.py --m unet3 --config configs/mimo-csi_U3.yml --dataset_type mimo --gpu 1 --mode train --n nni
trialCodeDirectory: .
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  gpuIndices: [0, 1, 2, 3]